Django 3, 4 support fix
last-partizan/pytils pull request #43
Opened 2022-02-19 11:52 UTC by temi4

Сделал минимальные изменения:
- убрал поддержку python2
- добавил поддержку django 3 и 4
- убрал поддержку django 1 и 2 
- обновил django-nose до nose2
- все тесты поправил и проверил, все прошло и работает (на М1 нет рабочих python3.6, 3.7 на них проверить не смог)
- сам код не причесывал (если нужно смогу сделать следующем PR)

2022-02-19 12:16 UTC, last-partizan requested changes

2022-02-19 12:16 UTC, last-partizan commented on .gitignore
> +/poetry.lock
pyproject и poetry.lock я думаю можно коммитить, это же тестовое dev-окружение? оно будет полезно.

2022-02-19 12:16 UTC, last-partizan commented on doc/examples-django/pytilsex/settings.py
> +BASE_DIR = CURRPATH
Вот так лучше не не делать, лучше просто везде заменить CURRPATH на BASE_DIR

2022-02-19 12:16 UTC, last-partizan commented on doc/examples/numeral.in_words.py
>      # то для Py2.x нужно использовать перекодировку в utf-8
Комментарии про python2 тоже надо удалить

2022-02-19 12:16 UTC, last-partizan commented on pytils/templatetags/pytils_numeral.py
> +except ImportError:
Вот этот try/except теперь же можно убрать

2022-02-19 12:16 UTC, last-partizan commented on pytils/templatetags/pytils_translit.py
> +except ImportError:
И этот try/except убираем

2022-02-19 12:16 UTC, last-partizan commented on pytils/test/templatetags/helpers.py
> +        # output = loader.get_template(template_name).render(template.Context(context))
А почему тут закомментирован тест?

2022-02-19 12:19 UTC, last-partizan commented
Если собираешься и дальше причёсывать код, это отлично, но было бы неплохо для начала настроить запуск тестов через github actions, и наверное заменить раннер тестов с nose на pytest. Это уже после этого PR, тут всё отлично, кроме тех комментариев что я отписал.

2022-02-19 12:27 UTC, last-partizan commented on Changelog
> + -- Yury Yurevich <the.pythy@gmail.com>  Thu, 16 Feb 2022
А тут наверное надо указать твоё имя и адрес :)

2022-02-20 03:28 UTC, temi4 commented on .gitignore
> +/poetry.lock
Добавил, да я использовал, чтобы pycharm зависимости подтянул

2022-02-20 03:28 UTC, temi4 commented on doc/examples-django/pytilsex/settings.py
> +BASE_DIR = CURRPATH
пофиксил

2022-02-20 03:29 UTC, temi4 commented on doc/examples/numeral.in_words.py
>      # то для Py2.x нужно использовать перекодировку в utf-8
удалил

2022-02-20 03:29 UTC, temi4 commented on pytils/templatetags/pytils_numeral.py
> +except ImportError:
убрал и заменил smart_text на smart_str в коде

2022-02-20 03:29 UTC, temi4 commented on pytils/templatetags/pytils_translit.py
> +except ImportError:
убрал и заменил smart_text на smart_str в коде

2022-02-20 03:31 UTC, temi4 commented on pytils/test/templatetags/helpers.py
> +        # output = loader.get_template(template_name).render(template.Context(context))
я немного его изменил, пока просто комментирование не удалил, чтобы ты видел изменения. 
тк иначе при get_template(template_name) - вываливается ошибка, что такой шаблон не найден.

Сейчас проще можно сделать: в Template передаем строку, которую нужно отрендерить и все

2022-02-20 03:31 UTC, temi4 commented on Changelog
> + -- Yury Yurevich <the.pythy@gmail.com>  Thu, 16 Feb 2022
:)

2022-02-20 03:39 UTC, temi4 commented
Давай просто согласуем список задач/идей. Что для тебя важно, чтобы изменилось. Я какие-то свои предложения внесу. И в следующем PR их сделаю.

2022-02-20 09:07 UTC, last-partizan commented on doc/examples-django/pytilsex/settings.py
> +    # 'django_nose',
```suggestion
```

2022-02-20 09:07 UTC, last-partizan commented on doc/examples-django/pytilsex/settings.py
> +# TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
```suggestion
```

2022-02-20 09:11 UTC, last-partizan commented on pytils/test/templatetags/helpers.py
> +# django.setup()
Вот такие закоментированные куски тоже не нужны, потому что непонятно зачем они.

2022-02-20 09:13 UTC, last-partizan commented on pytils/test/templatetags/helpers.py
> +        # output = loader.get_template(template_name).render(template.Context(context))
Наверное это всё-таки связано с тем что в helpers не указаны никакие TEMPLATE_DIRS, и это можно исправить.

Сейчас лучше это не переделывать, а исправить чтобы работал старый вариант.

2022-02-20 09:27 UTC, last-partizan commented on pytils/test/test_numeral.py
> +        self.checkChoosePlural(int(109), u"гвоздей")
```suggestion
```

Это даже можно удалить совсем, потому что `int(109)` это просто 109.

2022-02-20 09:29 UTC, last-partizan commented on pytils/test/test_numeral.py
> +        self.assertEquals(pytils.numeral.rubles(int(3)),
И вот это тоже удаляем, проверь другие случаи с int самостоятельно.

2022-02-20 09:31 UTC, last-partizan commented on pytils/utils.py
> +    assert isinstance(ustring, str), "uvalue must be unicode, not %s" % type(ustring)
```suggestion
    assert isinstance(ustring, str), "uvalue must be str, not %s" % type(ustring)
```

2022-02-20 10:06 UTC, last-partizan commented
Github-actions я настроил, можешь смержиться с мастером и теперь тесты запустятся для всех версий что надо

2022-02-20 10:50 UTC, temi4 commented
> Github-actions я настроил, можешь смержиться с мастером и теперь тесты запустятся для всех версий что надо

Такие вопросы:
1) tox.ini [gh-actions] - тут питон2, он по идее уже не нужен, мне править файл?
2) test.yml мне выходит тоже подправить под свои задачи?

2022-02-20 11:18 UTC, temi4 commented on pytils/test/templatetags/helpers.py
> +        # output = loader.get_template(template_name).render(template.Context(context))
Смотри раньше ты получается хакал django.template.loader - подменяя loader.template_source_loaders = [test_template_loader,] на свою функцию test_template_loader, те по сути ты пытался вместо шаблона сгенерить шаблон из строки. 

Сейчас это не отрабатывает, джанга пишет:
django.template.exceptions.TemplateDoesNotExist: translify_filter
его действительно нет, и в целом не понятно зачем нужно передавать его и пытаться сейчас хакать django loader, если можно взять django.template.Template - передать в него template_string на прямую, вместо 
test_template_loader и он сгенерирует как раз такой же шаблон и выполнит его

Ну те смысл получиться тот же: он сгенерит шаблон из строки и потом применит к нему Context

Либо могу заменить на более сложную форму:
def test_template_loader(template_name, template_dirs=None):
    return Template(template_string)
loader.get_template = test_template_loader

Ну те я стараюсь сохранить смысл функции, только изменил ее на более простое решение.

2022-02-20 12:53 UTC, temi4 commented on pytils/test/test_numeral.py
> +        self.assertEquals(pytils.numeral.rubles(int(3)),
готово

2022-02-20 12:54 UTC, temi4 commented on pytils/test/templatetags/helpers.py
> +# django.setup()
готово

2022-02-20 12:56 UTC, temi4 commented
Настройки для тестов пофиксил. Все работает гуд. Тесты прошли

2022-02-21 14:34 UTC, last-partizan commented on pytils/test/templatetags/helpers.py
> +        t = Template(template_string)
Тут всё супер, но у функции `check_template_tag` остался неиспользуемый параметр template_name. Его теперь нужно убрать.

2022-02-22 08:12 UTC, temi4 commented on pytils/test/templatetags/helpers.py
> +        t = Template(template_string)
Пофиксил

2022-02-22 13:16 UTC, last-partizan commented
Зря, конечно, ты в этом же мерже поубирал префиксы "u", это только усложнило ревью.

Лучше бы это было сделать потом. Но ладно, всё вроде окей, мержу.

2022-02-22 13:17 UTC, merged